NSCLC_normlize_centered<-read.table("G:/GSE99254/GSE99254_NSCLC.TCell.S11769.norm.centered.txt",sep = "\t",header = TRUE,row.names = 1)
NSCLC_count<-read.table("G:/GSE99254/GSE99254_NSCLC.TCell.S12346.count.txt",sep = "\t",header = TRUE,row.names = 1)
NSCLC_TPM<-read.table("G:/GSE99254/GSE99254_NSCLC.TCell.S12346.TPM.txt",header = TRUE,sep = "\t",row.names = 1)

library(dplyr)
NSCLC_count_PTR<-select(NSCLC_count,starts_with("PTR"))
NSCLC_count_TTR<-select(NSCLC_count,starts_with("TTR"))
NSCLC_TPM_PTR<-select(NSCLC_TPM,starts_with("PTR"))
NSCLC_TPM_TTR<-select(NSCLC_TPM,starts_with("TTR"))
NSCLC_normlize_centered_PTR<-select(NSCLC_normlize_centered,starts_with("PTR"))
NSCLC_normlize_centered_TTR<-select(NSCLC_normlize_centered,starts_with("TTR"))
NSCLC_count_PTR_TTR<-select(NSCLC_count,starts_with("PTR"),starts_with("TTR"))
NSCLC_TPM_PTR_TTR<-select(NSCLC_TPM,starts_with("PTR"),starts_with("TTR"))
NSCLC_normlize_centered_PTR_TTR<-select(NSCLC_normlize_centered,starts_with("PTR"),starts_with("TTR"))

library(cowplot)
library(Seurat)

NSCLC_count_PTR_seurat  <- CreateSeuratObject(counts =NSCLC_count_PTR, project = "NSCLC_count_PTR", min.cells = 3, min.features = 200)
VlnPlot(NSCLC_count_PTR_seurat, features = c("nFeature_RNA", "nCount_RNA"), ncol = 3)
NSCLC_count_PTR_seurat <- subset(NSCLC_count_PTR_seurat, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 )
NSCLC_count_PTR_seurat <- NormalizeData(NSCLC_count_PTR_seurat, verbose = FALSE)
NSCLC_count_PTR_seurat <- FindVariableFeatures(NSCLC_count_PTR_seurat, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(NSCLC_count_PTR_seurat)
NSCLC_count_PTR_seurat <- ScaleData(NSCLC_count_PTR_seurat, features = all.genes)
NSCLC_count_PTR_seurat <- RunPCA(NSCLC_count_PTR_seurat, features = VariableFeatures(object = NSCLC_count_PTR_seurat))
ElbowPlot(NSCLC_count_PTR_seurat)
NSCLC_count_PTR_seurat <- FindNeighbors(NSCLC_count_PTR_seurat, dims = 1:10)
NSCLC_count_PTR_seurat <- FindClusters(NSCLC_count_PTR_seurat, resolution = 0.5)
NSCLC_count_PTR_seurat <- RunUMAP(NSCLC_count_PTR_seurat, dims = 1:10)
DimPlot(NSCLC_count_PTR_seurat, reduction = "umap")

NSCLC_count_PTR_nomrlize_scaledata<-NSCLC_count_PTR_seurat@assays[["RNA"]]@scale.data
NSCLC_count_PTR_nomrlize_scaledata<-as.data.frame(NSCLC_count_PTR_nomrlize_scaledata)

NSCLC_count_PTR_nomrlize_scaledata_t<-t(NSCLC_count_PTR_nomrlize_scaledata)
NSCLC_count_PTR_nomrlize_scaledata_t<-as.data.frame(NSCLC_count_PTR_nomrlize_scaledata_t)

IL2_stat5<-read.table("g:/GSE98638/IL2_STAT5_entrezID.txt",sep = "\t",header = TRUE)
IL6_stat3<-read.table("g:/GSE98638/IL6_STAT3_entrezID.txt",sep = "\t",header = TRUE)

IL2_stat5<-IL2_stat5[2:200,]
IL6_stat3<-IL6_stat3[2:88,]

NSCLC_count_PTR_seurat <- CellCycleScoring(NSCLC_count_PTR_seurat, s.features = IL2_stat5, g2m.features = IL6_stat3, set.ident = FALSE)
IL2_stat5_list<-list(IL2_stat5)
IL6_stat3_list<-list(IL6_stat3)
NSCLC_count_PTR_seurat <- AddModuleScore(NSCLC_count_PTR_seurat,features = IL2_stat5_list,name = "IL2_stat5")
NSCLC_count_PTR_seurat <- AddModuleScore(NSCLC_count_PTR_seurat,features = IL6_stat3_list,name = "IL6_stat3")
JMJD1C<-select(NSCLC_count_PTR_nomrlize_scaledata_t,starts_with("221037"))
NRP1<-select(NSCLC_count_PTR_nomrlize_scaledata_t,starts_with("8829"))
Pdcd1<-select(NSCLC_count_PTR_nomrlize_scaledata_t,starts_with("5133") & ends_with("5133"))
Ifng<-select(NSCLC_count_PTR_nomrlize_scaledata_t,starts_with("3458") & ends_with("3458"))
IL2_stat5_score<-as.data.frame(NSCLC_count_PTR_seurat$IL2_stat51)
IL6_stat3_score<-as.data.frame(NSCLC_count_PTR_seurat$IL6_stat31)
data<-cbind(IL2_stat5_score,IL6_stat3_score,JMJD1C,Pdcd1,Ifng,NRP1)
colnames(data)<-c("IL2_stat5","IL6_stat3","JMJD1C","Pdcd1","Ifng","NRP1")
#library(corrplot)
#corrplot(matrix, method = "color")  

library(ggplot2)
library(ggpubr)
ggplot(data = data,aes(x=IL2_stat5,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new<-filter(data,IL2_stat5>0 & JMJD1C>0)
ggplot(data = data_new,aes(x=IL2_stat5,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=IL6_stat3,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new2<-filter(data,IL6_stat3>0 & JMJD1C>0)
ggplot(data = data_new2,aes(x=IL6_stat3,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new2,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=Pdcd1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new3<-filter(data,Pdcd1>0 & JMJD1C>0)
ggplot(data = data_new3,aes(x=Pdcd1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new3,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=Ifng,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new4<-filter(data,Ifng>0 & JMJD1C>0)
ggplot(data = data_new4,aes(x=Ifng,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new4,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=NRP1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new5<-filter(data,NRP1>0 & JMJD1C>0)
ggplot(data = data_new5,aes(x=NRP1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new5,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 


NSCLC_count_TTR_seurat  <- CreateSeuratObject(counts =NSCLC_count_TTR, project = "NSCLC_count_TTR", min.cells = 3, min.features = 200)
VlnPlot(NSCLC_count_TTR_seurat, features = c("nFeature_RNA", "nCount_RNA"), ncol = 3)
NSCLC_count_TTR_seurat <- subset(NSCLC_count_TTR_seurat, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 )
NSCLC_count_TTR_seurat <- NormalizeData(NSCLC_count_TTR_seurat, verbose = FALSE)
NSCLC_count_TTR_seurat <- FindVariableFeatures(NSCLC_count_TTR_seurat, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(NSCLC_count_TTR_seurat)
NSCLC_count_TTR_seurat <- ScaleData(NSCLC_count_TTR_seurat, features = all.genes)
NSCLC_count_TTR_seurat <- RunPCA(NSCLC_count_TTR_seurat, features = VariableFeatures(object = NSCLC_count_TTR_seurat))
ElbowPlot(NSCLC_count_TTR_seurat)
NSCLC_count_TTR_seurat <- FindNeighbors(NSCLC_count_TTR_seurat, dims = 1:10)
NSCLC_count_TTR_seurat <- FindClusters(NSCLC_count_TTR_seurat, resolution = 0.5)
NSCLC_count_TTR_seurat <- RunUMAP(NSCLC_count_TTR_seurat, dims = 1:10)
DimPlot(NSCLC_count_TTR_seurat, reduction = "umap")

NSCLC_count_TTR_nomrlize_scaledata<-NSCLC_count_TTR_seurat@assays[["RNA"]]@scale.data
NSCLC_count_TTR_nomrlize_scaledata<-as.data.frame(NSCLC_count_TTR_nomrlize_scaledata)

NSCLC_count_TTR_nomrlize_scaledata_t<-t(NSCLC_count_TTR_nomrlize_scaledata)
NSCLC_count_TTR_nomrlize_scaledata_t<-as.data.frame(NSCLC_count_TTR_nomrlize_scaledata_t)

IL2_stat5<-read.table("g:/GSE98638/IL2_STAT5_entrezID.txt",sep = "\t",header = TRUE)
IL6_stat3<-read.table("g:/GSE98638/IL6_STAT3_entrezID.txt",sep = "\t",header = TRUE)

IL2_stat5<-IL2_stat5[2:200,]
IL6_stat3<-IL6_stat3[2:88,]

NSCLC_count_TTR_seurat <- CellCycleScoring(NSCLC_count_TTR_seurat, s.features = IL2_stat5, g2m.features = IL6_stat3, set.ident = FALSE)
IL2_stat5_list<-list(IL2_stat5)
IL6_stat3_list<-list(IL6_stat3)
NSCLC_count_TTR_seurat <- AddModuleScore(NSCLC_count_TTR_seurat,features = IL2_stat5_list,name = "IL2_stat5")
NSCLC_count_TTR_seurat <- AddModuleScore(NSCLC_count_TTR_seurat,features = IL6_stat3_list,name = "IL6_stat3")
JMJD1C<-select(NSCLC_count_TTR_nomrlize_scaledata_t,starts_with("221037"))
NRP1<-select(NSCLC_count_TTR_nomrlize_scaledata_t,starts_with("8829"))
Pdcd1<-select(NSCLC_count_TTR_nomrlize_scaledata_t,starts_with("5133") & ends_with("5133"))
Ifng<-select(NSCLC_count_TTR_nomrlize_scaledata_t,starts_with("3458") & ends_with("3458"))
IL2_stat5_score<-as.data.frame(NSCLC_count_TTR_seurat$IL2_stat51)
IL6_stat3_score<-as.data.frame(NSCLC_count_TTR_seurat$IL6_stat31)
data<-cbind(IL2_stat5_score,IL6_stat3_score,JMJD1C,Pdcd1,Ifng,NRP1)
colnames(data)<-c("IL2_stat5","IL6_stat3","JMJD1C","Pdcd1","Ifng","NRP1")
#library(corrplot)
#corrplot(matrix, method = "color")  

library(ggplot2)
library(ggpubr)
ggplot(data = data,aes(x=IL2_stat5,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new<-filter(data,IL2_stat5>0 & JMJD1C>0)
ggplot(data = data_new,aes(x=IL2_stat5,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=IL6_stat3,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new2<-filter(data,IL6_stat3>0 & JMJD1C>0)
ggplot(data = data_new2,aes(x=IL6_stat3,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new2,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=Pdcd1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new3<-filter(data,Pdcd1>0 & JMJD1C>0)
ggplot(data = data_new3,aes(x=Pdcd1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new3,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=Ifng,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new4<-filter(data,Ifng>0 & JMJD1C>0)
ggplot(data = data_new4,aes(x=Ifng,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new4,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=NRP1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new5<-filter(data,NRP1>0 & JMJD1C>0)
ggplot(data = data_new5,aes(x=NRP1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new5,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
